# Constants

CONST_AREA_THRESHOLD = 20
CONST_FLAME_THRESHOLD = 10

# Given ROI

CONST_UPPER_LEFT_X = 570
CONST_UPPER_LEFT_Y = 40
CONST_BOTTOM_RIGHT_X = 637
CONST_BOTTOM_RIGHT_Y = 94



# False Flame

#CONST_UPPER_LEFT_X = 201
#CONST_UPPER_LEFT_Y = 163
#CONST_BOTTOM_RIGHT_X = 335
#CONST_BOTTOM_RIGHT_Y = 223

#Smoke Part

#CONST_UPPER_LEFT_X = 391
#CONST_UPPER_LEFT_Y = 65
#CONST_BOTTOM_RIGHT_X = 546
#CONST_BOTTOM_RIGHT_Y = 167